development:
  adapter: mysql2
  encoding: utf8
  database: listings_development
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: listings_test
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: listings_production
  pool: 5
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
